export const SORT_PRODUCTS_LOW_HIGH = 'SORT_PRODUCTS_LOW_HIGH';
export const SORT_PRODUCTS_HIGH_LOW = 'SORT_PRODUCTS_HIGH_LOW';
export const SORT_PRODUCTS_BY_DISCOUNT = 'SORT_PRODUCTS_BY_DISCOUNT';
export const FILTER_PRODUCT_BY_PRICERANGE = 'FILTER_PRODUCT_BY_PRICERANGE';
